apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"
  name: azure-vote-front
  namespace: default
spec:
  rules:
  - host: predscaling01.natzkalabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: azure-vote-front
            port:
              number: 80
  tls:
    - hosts:
      - predscaling01.natzkalabs.com
      secretName: predscaling01-tls

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-stack-kube-prom-nginx
  namespace: monitoring
  labels:
    app: nginx-ingress
    release: prometheus-stack
spec:
  endpoints:
  - interval: 10s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
    - ingress

# INGRESS FOR PROMETHEUS AND GRAFANA IS DEPLOYED BY PROMETHEUS HELM CHART
  
# ---

# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: prom-adapter
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: azure-vote-back
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Object
#     object:
#       metric:
#         name: nginx_ingress_controller_requests
#       describedObject:
#         apiVersion: networking.k8s.io/v1beta1
#         kind: ingress
#         name: azure-vote-front
#       target:
#         type: Value
#         value: "1"

# --- 
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#     # nginx.ingress.kubernetes.io/configuration-snippet: |
#     #   rewrite ^(/grafana)$ $1/ redirect;
#   name: grafana
#   namespace: monitoring
# spec:
#   rules:
#     - host: predscaling01.natzkalabs.com
#       http:
#         paths:
#           - path: /grafana(/|$)(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: grafana
#                 port:
#                   number: 80
#   tls:
#     - hosts:
#       - predscaling01.natzkalabs.com
#       secretName: dpredscaling01-tls


# --- 
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # nginx.ingress.kubernetes.io/ssl-redirect: "true"
#     # nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /prometheus/$1
#   name: prometheus
#   namespace: monitoring
# spec:
#   rules:
#     - host: predscaling01.natzkalabs.com
#       http:
#         paths:
#           - path: /prometheus
#             pathType: Prefix
#             backend:
#               service:
#                 name: prometheus-server
#                 port:
#                   number: 80
#   tls:
#     - hosts:
#       - predscaling01.natzkalabs.com
#       secretName: predscaling01-tls